### ISSUE TITLE
Improvements to Timings

### ISSUE THREAD

**Issue by Volgeop** [kangarko/Confiscate#104]
Hi, could you please make improvements to timings? I have in my settings:
```
  #
  # Scan players' inventories when they log in, die or change worlds?
  # This is compatible with per world inventory plugins.
  #
  Inventories: false
  #
  # Scan players' inventories each time they right or left click with an item?
  # Enabling might impose a slight performance penalty.
  #
  When_Clicking: false
  #
  # Scan players' inventories when they issue commands below? We wait a bit in case
  # they change worlds, gamemode or similar.
  #
  # NOTICE: Requres 'Inventories' enabled.
  #
  On_Command:
  - /warp
  - /res
  - /home
  - /tpa
  - /trade
  - /give
  #
  # Scan containers (chests, furnaces, enchant tables, etc.) when players open them?
  #
  Containers:
    #
    # Do the scan?
    #
    Enabled: true
    #
    # Which containers to ignore? For names, see:
    # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/InventoryType.html
    #
    Ignored: [ANVIL]
```

and in my timings is 
And improvements to Timings?
```
Confiscate::Event: o.m.c.i. .cG (InventoryOpenEvent)
count(2) total(0.52% 0.089s, 0.92% of tick)
avg(44.55ms per - 0.46ms/0.01 per tick
```
https://timings.aikar.co/?id=d7837105e1c4497c9679a83da6e153b5
So maybe could be a little bit improved. 

Believe it will be useful also for another servers, because no one like lags :D, and yes, you can just modify your actual system.
