### ISSUE TITLE
1.18: Confiscate doesn't recognize SWEEPING_EDGE

### ISSUE THREAD

**Issue by HgeX** [kangarko/Confiscate#134]
Hi!

The title pretty much says it all, Confiscate throws a nice error instead of starting as it should. According to the logs, `SWEEPING_EDGE` is an invalid enchantment name, however, opening the suggested link says otherwise:

`static final Enchantment SWEEPING_EDGE - Increases damage against targets when using a sweep attack`

The problem occurs when adding the enchantment to the **Enchants.Too_High.Exceptions** section. In my case that looks something like this *(problematic line seems to be the last one)*:
```yaml
  Enchants:
    Allow_Strictness: 1
    Lore_Whitelist:
      - "A Boss egg|This is a Boss egg" # ignore lore with first line containing "A Boss egg" and the second line containing "This is a Boss egg"
    Supply_With_Unenchanted: false
    Non_Applicable:
      Enabled: false
      Exceptions:
        - THORNS
    Too_High:
      Enabled: true
      Exceptions:
        SILK_TOUCH: 2
        SWEEPING_EDGE: 6
```

The interesting part is the error message though, which is: `Error: Report: Invalid enchantment 'SWEEPING'! For valid names, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html`. It looks like it's checking SWEEPING rather then SWEEPING_EDGE, in which case it's clear why the check fails.

You can find the full error here: https://pastebin.com/H7N5f1qn
And the full configuration here *(not that it would be of much use, it's basically the default configuration)*:  https://pastebin.com/HC1EtxE4

**Steps to reproduce:**
1) Add `SWEEPING_EDGE` to **Enchants.Too_High.Exceptions**
2) Start the server
